smallLike = 1000 # 抓取最小视频赞数,仅抓取大于此值的视频
isDownload = 1 # 是否下载远程 用户头像 封面图 视频 到本地  0否1是

[proxy]
addr = ":8080" #设置 proxy listen 端口

[app]
packageName = "com.ss.android.ugc.aweme" # 抖音app包名
startPath = ".main.MainActivity" # 抖音app包首页path
restart = 60 # 重新打开时间  单位秒
sleep = 60 # 重新打开睡眠时间  单位秒

[swipe]
# 滑动 开始和结束 像素坐标值
startX = 500
startY = 1000
endX = 489
endY = 123
sleep = 200 # 滑动等待时间  单位毫秒
